// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SUB.Data;

namespace SUB.Migrations
{
    [DbContext(typeof(SUBContext))]
    partial class SUBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SUB.Models.Wydarzenie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gosc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gospodarz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Remis")
                        .HasColumnType("real");

                    b.Property<int>("WynikWydarzenia")
                        .HasColumnType("int");

                    b.Property<float>("ZwyciestwoGosc")
                        .HasColumnType("real");

                    b.Property<float>("ZwyciestwoGospodarz")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Wydarzenie");
                });
#pragma warning restore 612, 618
        }
    }
}
